// Mock Data for Media Cards
import type { FeedCard } from '@/types/feed';

export const createMockData = (): FeedCard[] => {
  const authors = [
    { handle: 'photographer', displayName: 'Travel Photographer', seed: 'photo' },
    { handle: 'videographer', displayName: 'Content Creator', seed: 'video' },
    { handle: 'podcaster', displayName: 'English Podcaster', seed: 'podcast' },
    { handle: 'teacher', displayName: 'English Teacher', seed: 'teacher' },
    { handle: 'student', displayName: 'Language Student', seed: 'student' },
  ];

  const baseTime = Date.now();

  return [
    // Multi-Chapter Quest Card - Harry Potter
    {
      id: 'quest-harry-potter-multi-chapter',
      type: 'novel',
      author: {
        id: 'author-hp-quest',
        handle: 'ahalearn',
        displayName: 'Aha Learning',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahalearn',
        verified: true,
        badges: ['verified', 'organization'],
      },
      content: '🧙‍♂️ NEW: Multi-Chapter Harry Potter Quest! Experience the magical world through 3 immersive chapters. Read, practice conversations, and get personalized feedback from Harry himself! Perfect for A2 learners.',
      createdAt: new Date(baseTime - 1000 * 60 * 2).toISOString(),
      stats: { replies: 89, reposts: 234, likes: 1205, bookmarks: 456, views: 5600 },
      viewer: { liked: false, reposted: false, bookmarked: false },
      novel: {
        id: 'harry-potter-multi-chapter-a2',
        title: 'Harry Potter: The Boy Who Lived',
        excerpt: 'Harry Potter has never been the star of a Quidditch team, scoring points while riding a broom far above the ground. He knows no spells, has never helped to hatch a dragon, and has never worn a cloak of invisibility...',
        coverImage: 'https://images.unsplash.com/photo-1600189261867-30e5ffe7b8da?w=400&h=600&fit=crop',
        difficulty: 2,
        totalChapters: 3,
        currentChapter: 1,
        tags: ['Fantasy', 'Magic', 'Adventure', 'Multi-Chapter'],
        language: 'English',
        estimatedTime: '45 min',
        questType: 'multi-chapter',
      },
    },

    // Quest Card - The Visitors' Zoo
    {
      id: 'quest-novel-001',
      type: 'novel',
      author: {
        id: 'author-quest',
        handle: 'ahalearn',
        displayName: 'Aha Learning',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahalearn',
        verified: true,
        badges: ['verified', 'organization'],
      },
      content: '🚀 New Science Fiction Quest Available! Travel through time and discover what happens when humans accidentally change history. Are you ready for this mind-bending adventure?',
      createdAt: new Date(baseTime - 1000 * 60 * 5).toISOString(),
      stats: { replies: 42, reposts: 128, likes: 567, bookmarks: 234, views: 3400 },
      viewer: { liked: false, reposted: false, bookmarked: false },
      novel: {
        id: 'novel-001',
        title: 'The Visitors\' Zoo',
        excerpt: 'Emma and I were on our honeymoon in space. We visited the Moon and flew far away from Earth. But what we discovered would change everything...',
        coverImage: 'https://picsum.photos/seed/novel-zoo-dinosaur/600/900',
        difficulty: 3,
        totalChapters: 1,
        currentChapter: 1,
        tags: ['Science Fiction', 'Time Travel', 'Adventure'],
        language: 'English',
        estimatedTime: '8 min',
        questType: 'comprehension',
      },
    },

    // Single Image Card
    {
      id: 'single-image-1',
      type: 'image',
      author: {
        id: 'author-1',
        handle: authors[0].handle,
        displayName: authors[0].displayName,
        avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=${authors[0].seed}`,
        verified: true,
        badges: ['verified'],
      },
      content: 'Beautiful sunset from my recent trip! 🌅 Perfect for learning descriptive vocabulary.',
      createdAt: new Date(baseTime - 1000 * 60 * 30).toISOString(),
      stats: { replies: 15, reposts: 45, likes: 234, bookmarks: 67, views: 1200 },
      viewer: { liked: false, reposted: false, bookmarked: false },
      media: [
        {
          id: 'img-1',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=1',
          thumbnail: 'https://picsum.photos/400/300?random=1',
          alt: 'Beautiful sunset landscape',
          width: 800,
          height: 600,
          aspectRatio: '4/3',
        },
      ],
    },

    // Two Images Card
    {
      id: 'two-images-1',
      type: 'image',
      author: {
        id: 'author-2',
        handle: authors[1].handle,
        displayName: authors[1].displayName,
        avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=${authors[1].seed}`,
        verified: false,
      },
      content: 'Before and after: My English learning progress! 📚✨',
      createdAt: new Date(baseTime - 1000 * 60 * 60).toISOString(),
      stats: { replies: 8, reposts: 23, likes: 156, bookmarks: 34, views: 890 },
      viewer: { liked: true, reposted: false, bookmarked: false },
      media: [
        {
          id: 'img-2a',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=2',
          thumbnail: 'https://picsum.photos/400/300?random=2',
          alt: 'Before: Basic English',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
        {
          id: 'img-2b',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=3',
          thumbnail: 'https://picsum.photos/400/300?random=3',
          alt: 'After: Advanced English',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
      ],
    },

    // Three Images Card
    {
      id: 'three-images-1',
      type: 'image',
      author: {
        id: 'author-3',
        handle: authors[2].handle,
        displayName: authors[2].displayName,
        avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=${authors[2].seed}`,
        verified: true,
        badges: ['verified', 'organization'],
      },
      content: 'Step-by-step guide to English pronunciation! 🗣️ Practice these sounds daily.',
      createdAt: new Date(baseTime - 1000 * 60 * 90).toISOString(),
      stats: { replies: 25, reposts: 78, likes: 456, bookmarks: 123, views: 2100 },
      viewer: { liked: false, reposted: true, bookmarked: true },
      media: [
        {
          id: 'img-3a',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=4',
          thumbnail: 'https://picsum.photos/400/300?random=4',
          alt: 'Step 1: Mouth position',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
        {
          id: 'img-3b',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=5',
          thumbnail: 'https://picsum.photos/400/300?random=5',
          alt: 'Step 2: Tongue placement',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
        {
          id: 'img-3c',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=6',
          thumbnail: 'https://picsum.photos/400/300?random=6',
          alt: 'Step 3: Practice exercises',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
      ],
    },

    // Four Images Card
    {
      id: 'four-images-1',
      type: 'image',
      author: {
        id: 'author-4',
        handle: authors[3].handle,
        displayName: authors[3].displayName,
        avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=${authors[3].seed}`,
        verified: false,
      },
      content: 'My English learning setup! 📖💻 These tools helped me improve my vocabulary.',
      createdAt: new Date(baseTime - 1000 * 60 * 120).toISOString(),
      stats: { replies: 12, reposts: 34, likes: 189, bookmarks: 56, views: 1450 },
      viewer: { liked: true, reposted: false, bookmarked: false },
      media: [
        {
          id: 'img-4a',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=7',
          thumbnail: 'https://picsum.photos/400/300?random=7',
          alt: 'Study desk setup',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
        {
          id: 'img-4b',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=8',
          thumbnail: 'https://picsum.photos/400/300?random=8',
          alt: 'English books',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
        {
          id: 'img-4c',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=9',
          thumbnail: 'https://picsum.photos/400/300?random=9',
          alt: 'Language learning apps',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
        {
          id: 'img-4d',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=10',
          thumbnail: 'https://picsum.photos/400/300?random=10',
          alt: 'Progress tracking',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
      ],
    },

    // Five+ Images Card (with +N indicator)
    {
      id: 'five-images-1',
      type: 'image',
      author: {
        id: 'author-5',
        handle: authors[4].handle,
        displayName: authors[4].displayName,
        avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=${authors[4].seed}`,
        verified: false,
      },
      content: 'My English learning journey documented! 📸 From beginner to intermediate level.',
      createdAt: new Date(baseTime - 1000 * 60 * 150).toISOString(),
      stats: { replies: 18, reposts: 67, likes: 312, bookmarks: 89, views: 1800 },
      viewer: { liked: false, reposted: false, bookmarked: true },
      media: [
        {
          id: 'img-5a',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=11',
          thumbnail: 'https://picsum.photos/400/300?random=11',
          alt: 'Day 1: Starting out',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
        {
          id: 'img-5b',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=12',
          thumbnail: 'https://picsum.photos/400/300?random=12',
          alt: 'Week 1: First progress',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
        {
          id: 'img-5c',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=13',
          thumbnail: 'https://picsum.photos/400/300?random=13',
          alt: 'Month 1: Vocabulary growth',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
        {
          id: 'img-5d',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=14',
          thumbnail: 'https://picsum.photos/400/300?random=14',
          alt: 'Month 3: Conversation practice',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
        {
          id: 'img-5e',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=15',
          thumbnail: 'https://picsum.photos/400/300?random=15',
          alt: 'Month 6: Intermediate level',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
        {
          id: 'img-5f',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=16',
          thumbnail: 'https://picsum.photos/400/300?random=16',
          alt: 'Month 9: Advanced practice',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
      ],
    },

    // Video Card
    {
      id: 'video-1',
      type: 'image',
      author: {
        id: 'author-6',
        handle: 'videographer',
        displayName: 'English Video Creator',
        avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=video-creator`,
        verified: true,
        badges: ['verified', 'organization'],
      },
      content: '🎬 Quick English lesson: Common idioms and their meanings! Click play to learn!',
      createdAt: new Date(baseTime - 1000 * 60 * 180).toISOString(),
      stats: { replies: 35, reposts: 89, likes: 567, bookmarks: 145, views: 3200 },
      viewer: { liked: true, reposted: false, bookmarked: false },
      media: [
        {
          id: 'video-1',
          type: 'video',
          url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
          thumbnail: 'https://picsum.photos/800/450?random=20',
          alt: 'English idioms lesson video',
          width: 1280,
          height: 720,
          aspectRatio: '16/9',
          duration: 180, // 3 minutes
        },
      ],
    },

    // Audio Card
    {
      id: 'audio-1',
      type: 'audio',
      author: {
        id: 'author-7',
        handle: 'podcaster',
        displayName: 'English Podcaster',
        avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=podcaster`,
        verified: true,
        badges: ['verified'],
      },
      content: '🎧 New podcast episode: "Advanced English Conversation" - Perfect for intermediate learners!',
      createdAt: new Date(baseTime - 1000 * 60 * 210).toISOString(),
      stats: { replies: 22, reposts: 45, likes: 234, bookmarks: 78, views: 1500 },
      viewer: { liked: false, reposted: false, bookmarked: true },
      audio: {
        id: 'audio-1',
        url: 'https://www.soundjay.com/misc/sounds/bell-ringing-05.wav',
        title: 'Advanced English Conversation - Episode 15',
        duration: 420, // 7 minutes
        waveform: Array.from({ length: 50 }, () => Math.random()),
        coverImage: 'https://picsum.photos/400/400?random=30',
      },
    },

    // Mixed Media Card (Image + Video)
    {
      id: 'mixed-media-1',
      type: 'image',
      author: {
        id: 'author-8',
        handle: 'contentcreator',
        displayName: 'Multimedia English Teacher',
        avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=teacher`,
        verified: true,
        badges: ['verified', 'organization'],
      },
      content: '📚📹 Here\'s my complete English learning resource pack! Images + video tutorial.',
      createdAt: new Date(baseTime - 1000 * 60 * 240).toISOString(),
      stats: { replies: 28, reposts: 67, likes: 389, bookmarks: 112, views: 2100 },
      viewer: { liked: false, reposted: true, bookmarked: false },
      media: [
        {
          id: 'mixed-1a',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=25',
          thumbnail: 'https://picsum.photos/400/300?random=25',
          alt: 'Grammar reference sheet',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
        {
          id: 'mixed-1b',
          type: 'video',
          url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
          thumbnail: 'https://picsum.photos/800/450?random=26',
          alt: 'Grammar explanation video',
          width: 1280,
          height: 720,
          aspectRatio: '1',
          duration: 240, // 4 minutes
        },
        {
          id: 'mixed-1c',
          type: 'image',
          url: 'https://picsum.photos/800/600?random=27',
          thumbnail: 'https://picsum.photos/400/300?random=27',
          alt: 'Practice exercises',
          width: 800,
          height: 600,
          aspectRatio: '1',
        },
      ],
    },
  ];
};
